### ISSUE TITLE
Release build without the js file

### ISSUE THREAD

**Issue by renatoch** [jmbledsoe/angularjs-visualstudio-intellisense#15]
Hello,
First of all, great code! Helps a lot in the day to day stuff.
Question I have: I don't want to release the js file, just use it while developing. Any easy way to do that?
Cheers

**Comment by jmatthiesen** [comment]
I think John is right re: the build action, but the suggestion to edit JavaScript references likely won't work for you in this case - The angular.intellisense.js file is auto-loaded by Visual Studio right after loading angular.js (or angular.min.js) if it is present. When you add it as an explicit reference the editor won't load it correctly. Instead, there's a location in Program Files you can use and VS will automatically load the extension for you if it's found there, with no need to include it in your project.

From the README:
If you prefer to enable AngularJS intellisene for all of your web projects, simply save the angular.intellisense.js file to your %PROGRAMFILES%\Microsoft Visual Studio 12.0\JavaScript\References folder. %PROGRAMFILES% is the location of your program files folder, usually under C:\Program Files or C:\Program Files (x86).

**Comment by renatoch** [comment]
Thanks guys! That did the trick! (changing content type to none and do not copy).

Another question I have: The intellisense only work in .js files, right? Is there any way to make intellisense in c# .cshtml files, so that they don't show as unrecognized and red underlined?

Cheers

**Comment by jmbledsoe** [comment]
Jordan is the authority on this, but I am almost certain that you will only
get IntelliSense for JavaScript files in Visual Studio.
