### ISSUE TITLE
Nuget URL

### ISSUE THREAD

**Issue by embassem** [jmbledsoe/angularjs-visualstudio-intellisense#23]
Please put the Nuget Package and the URL 
and Please update it to angular 1.4  and 
Dependencies to latest Stable 
AngularJS.Core (≥ 1.3.15)

**Comment by jmbledsoe** [comment]
I actually haven't done anything with the NuGet package, as it was created by @cicorias. If you'd like to make the updates I will happily accept a pull request.

**Comment by cicorias** [comment]
Could you clarify what you mean by 'put the nuget package and URL'?

I think we may do an [approximate](http://docs.nuget.org/create/versioning#Specifying-Version-Ranges-in-.nuspec-Files) on the version then.

**Comment by embassem** [comment]
i mean to but this url in README.md and put the  installation command too  .


https://www.nuget.org/packages/AngularJS.Intellisense/
PM> Install-Package AngularJS.Intellisense 


the AngularJS.Core had updated to latest stable AngularJS Core 1.3.15 
i Suggest update the dependency  version="1.3.15" 

the package  Owner on NuGet  is  @cicorias  and @jmbledsoe

**Comment by cicorias** [comment]
Pull request created #24
