### ISSUE TITLE
Intellisense not working on Visual Studio 2015 CTP 6

### ISSUE THREAD

**Issue by eduaglz** [jmbledsoe/angularjs-visualstudio-intellisense#25]
According to this [post](http://blogs.msdn.com/b/visualstudio/archive/2015/02/05/using-angularjs-in-visual-studio-2013.aspx) intellisense should also be working on the new VS 2015, but so far I only get intellisense for the angular object and not for the dependencies or my custom modules.

![image](https://cloud.githubusercontent.com/assets/5376927/7302873/0ff0620c-e9b2-11e4-89ff-97d090131f4e.png)

Here's what I did:
1  Added the angular.intellisense.js to the global javascript references at 
> C:\Program Files (x86)\Microsoft Visual Studio 14.0\JavaScript\References
2 Restarted VS2015
And then nothing, it just showed exclamation marks whenever I tried to use intellisense on a $http object.

I also added the file to the same place as my angular.js but it still didn't work. The question that I have in this case is, where should I place the file? on the angular public folder with only my angular.js, or on my dev angular folder where all the files downloaded from bower are.

I also tried addind it directly into the tools/options/text editor/javascriptr/intellisense/reference menu, on the Implicit(Web) reference group, but it still didn't work.

On my project I have the following folder structure inside the src folder:

- wwwroot
    - app (my angular site stuff)
         - controllers
         - services
         - views
    - lib (js dependencies, only the .min.js file of each library)
         - angular
         - angular-route
         - ....
    - _references.js (the visual studio js references file, contains reference to the files inside the app and lib folders)
- Libraries (contains the full libraries as downloaded by bower)
    - angular
    - angular-route
    - ...

As a side note, I don't have a /scripts folder and therefore no /scripts/_references.js file

.

**Comment by jmbledsoe** [comment]
I am fairly certain that you're going to need a _reference.js file that
lists your scripts in a reasonable order i.e. the same order in which they
appear in your application. Otherwise VS can't find the files that declare
your dependencies.

**Comment by eduaglz** [comment]
I do have a _references.js, but it is under /wwwroot rather than on the /scripts folder.
This is the content of the file:

```
/// <autosync enabled="false" />
/// <reference path="lib/jquery/js/jquery.js" />
/// <reference path="lib/angular/angular.js" />
/// <reference path="lib/angular-route/angular-route.js" />
/// <reference path="lib/angular-animate/angular-animate.js" />
/// <reference path="lib/angular-mocks/angular-mocks.js" />
/// <reference path="lib/bootstrap/js/bootstrap.js" />
/// <reference path="lib/bootstrap/js/npm.js" />
/// <reference path="lib/flatstrap/js/flatstrap.js" />
/// <reference path="lib/flatstrap/js/npm.js" />
/// <reference path="lib/iCheck/icheck.min.js" />
/// <reference path="lib/underscore/underscore.js" />
/// <reference path="app/app.js" />
/// <reference path="app/controllers/HomeController.js" />
/// <reference path="app/controllers/NavbarController.js" />
/// <reference path="app/controllers/account/AccountController.js" />
/// <reference path="app/controllers/account/LoginController.js" />
/// <reference path="app/controllers/account/RegisterController.js" />
/// <reference path="app/services/AccountService.js" />
/// <reference path="app/services/AuthService.js" />
/// <reference path="tests/AuthServiceTests.js" />
```

**Comment by jmbledsoe** [comment]
That could be your problem. See the linked post which describes how VS uses
_references.js

http://madskristensen.net/post/the-story-behind-_referencesjs

**Comment by jmbledsoe** [comment]
By "your problem" I mean that _references.js is not in the Scripts folder.
Try moving the file and see if it helps.

**Comment by eduaglz** [comment]
I also thought It could be that, but VS also has a reference to the _references.js under wwwRoot, so that shouldn't be a problem:

![image](https://cloud.githubusercontent.com/assets/5376927/7304302/2990f9ec-e9bc-11e4-95ad-979d5308c0ca.png)

Even so, I tried moving it to that location as you said but got the same result

**Comment by eduaglz** [comment]
Under the Output windows I'm getting the following message:
![image](https://cloud.githubusercontent.com/assets/5376927/7304787/169dbaac-e9bf-11e4-8f71-2c557eddbea5.png)

I don't know if this might be the reason, but I already checked and I do have the files on that location so I don't know why VS is not able to load them.

![image](https://cloud.githubusercontent.com/assets/5376927/7304835/647d4f76-e9bf-11e4-8d70-7deb00d9c3db.png)

**Comment by jmbledsoe** [comment]
Hmm...I'm not sure there is much I can do with it. I actually haven't done anything with VS 2015 support yet; it's all been @jmatthiesen. It looks like your setup is fine.

**Comment by jmatthiesen** [comment]
What version of Visual Studio 2015 (available from the Help | About... menu) are you using? I saw this recently myself.

**Comment by eduaglz** [comment]
This is the version that I have:
> Microsoft Visual Studio Ultimate 2015 CTP
Version 14.0.22609.0 D14REL
Microsoft .NET Framework
Version 4.6.00030
Installed Version: Ultimate

**Comment by eduaglz** [comment]
The issue is gone after installing the RC version of Visual Studio 2015.

**Comment by GregLarden** [comment]
I have current release version and it still does not work. My script paths are in App_Start\BundleConfig.cs. Could this be why?

**Comment by jmbledsoe** [comment]
@GregLarden if you have a project file that demonstrates the issue that would help with diagnosis. Create a new issue if you like and include a link to the project, and I should be able to see what is causing the error.

**Comment by GregLarden** [comment]
thank you for the help! I have to make a sample project as this is company project that is not working. I will do a hottowel template.

**Comment by GregLarden** [comment]
@jmbledsoe Hi, so I have a repository with the sample project demonstrating the intellisense issue.

Repository name is: VS2015-Angular-Intellisense-Test

Do we need a new issue or can we just reopen this one? I'm sure a lot of people are having this issue.

Hope this helps.. again I really appreciate the help!

**Comment by cgsainty** [comment]
I've been having very similar problems with intellisense when trying to write Jasmine unit tests in a Test project. I have created a _references.js file in a scripts folder in the project but I get no intellisense when writing my tests.

**Comment by jmbledsoe** [comment]
@cgsainty So far what I've been finding is that issues are project-specific, so if you have a sample project that demonstrates the issue, please create a new issue pointing to it and include a link to the sample project. Thanks!

**Comment by haydenhancock** [comment]
Just a heads up. If you create a new ASP.NET Web Application using the "Empty" ASP.NET 5 Preview Template, you won't get a _references.js file. It can be fixed easily...
1. Right-click your project name and select Add > New Item...
2. From the "Installed" view, click Client-side, then select JavaScript File. Give it a name of _references.js and click Add.
3. Right-click your newly created _references.js file. Select Auto-sync JavaScript References

The cool thing is that it doesn't seem to really matter where you put this file. Make sure you have selected the auto-sync feature though.

**Comment by Seefer1** [comment]
I'm a noob using some third party javascript libraries such as D3.JS because data visualisation light my fusion reactor and it's my chosen subject to play with as I learn this arcane web dev trickery.

D3 works just fine with apparently full Intellisense support thanks to the **_references.js** feature (thanks Mads!).

However, it seems some javascript libraries are just plain uncooperative.  For example I've just started using **topojson.js** and despite adding this to **_references.js** I still get yellow exclamation marks in the completion list when accessing this object.

Looking at the **d3.js** source code I see it begins its code with `!function()` whereas **topojson.js** lacks the ! character before its function keywork. I'm still learning so I'm not entirely sure how the ! relates to problems with Intellisense in VS2015. Being curious though I just put a ! character at the start of the topojson.js source and Intellisense seems to work, though I'm not sure if doing this is going to break things in topojson. Is this all something to do with javascript global scope and am I okay to just slap that ! in front of topojsons function declaration?
