### ISSUE TITLE
Ionic's AngularJS Intellisense in Visual Studio 2015 Tools for Apache Cordova Project

### ISSUE THREAD

**Issue by waynebloss** [jmbledsoe/angularjs-visualstudio-intellisense#29]
I was not getting Intellisense for Angular inside of `*.js` files in a VS2015 [Tools for Apache Cordova](https://www.visualstudio.com/en-us/features/cordova-vs.aspx) project that uses [Ionic](https://github.com/driftyco/ionic), which bundles it's own copy of Angular.

So, I copied the latest [angular.intellisense.js file](https://raw.githubusercontent.com/jmbledsoe/angularjs-visualstudio-intellisense/master/src/Scripts/angular.intellisense.js) from this repo and placed it in my project as `~/www/lib/ionic/js/ionic.intellisense.js`. This worked beautifully after restarting VS (*probably not necessary*) and then activating it in one of my `*.js` files (*by typing `$http.` a few times and then waiting about 10 seconds*). It also works for my own internal services, which reside in separate js files in my `~/www/services` folder.

Just wanted to let others know. Thanks for your work!

**Comment by jmbledsoe** [comment]
Since this seems to be just informational, I'll close this issue. Thanks for the note.
