### ISSUE TITLE
Intellisense not working in existing modules in Visual Studio 2015

### ISSUE THREAD

**Issue by ltlombardi** [jmbledsoe/angularjs-visualstudio-intellisense#33]
I have everything well configured with the _references.js file, and I get intellisense for other libraries, like jQUERY, but I can't get it to work properly for AngularJS.

For example. in the bellow picture I'm creating a new module and adding a directive and I get intellisense for the $http angular object, which is fine.

![jmbql](https://cloud.githubusercontent.com/assets/898124/13961864/2eaabca0-f03d-11e5-806e-855a3de996d5.png)

But in the bellow picture the module is already created and so I don't put the empty array in the module declaration. If I did, it would overwrite any previous declared module, rendering my app useless. Even though everything works fine with the code, intellisense is gone:
![uaftk](https://cloud.githubusercontent.com/assets/898124/13961867/33b78a02-f03d-11e5-9557-d1ec73bbf817.png)

I've been searching for more than a month. Any ideas?

**Comment by jmbledsoe** [comment]
This has to be a _references.js issue. If the Intellisense engine can't find the module declaration in a file referenced there then it won't be able to spin up AngularjS.

If you post a sample project that demonstrates the issue I will take a look.

**Comment by ltlombardi** [comment]
@jmbledsoe, thank you!
I ziped everything but the packages and .vs folder. Hope it's enough.
[WebApplication1.zip](https://github.com/jmbledsoe/angularjs-visualstudio-intellisense/files/198010/WebApplication1.zip)

**Comment by jmbledsoe** [comment]
Move angular.js and angular-mocks.js ahead of your application files in _references.js. Files in _references.js need to be in the same order as they are in your index.html for Intellisense to know what to do with them.

**Comment by ltlombardi** [comment]
Again, thank you very much. This fixed it. 

I didn't find this information anywhere. I imagine this happens to 99% of users, because the "update javascript references" command  that auto add every JS file in the _references.js doesn't care about the order, nor does it gives any warning nor any of the documentation do. not that I could find.

**Comment by jmbledsoe** [comment]
Yeah the docs need updated. Feel free to create a PR!

**Comment by ltlombardi** [comment]
I want to give back to the community. I'm planning to do a complete guide about VS Intellisense, including AngularJS. I never did a pull request. It's gonna be my pleasure doing it for the first time. :smile:

**Comment by jmbledsoe** [comment]
Awesome! Thanks!
