### ISSUE TITLE
The ordering of three slash references

### ISSUE THREAD

**Issue by epicbugs** [jmbledsoe/angularjs-visualstudio-intellisense#5]
Thanks for this awesome extension!

But I do have a small request - please do mention under the "Usage" section of its github page that "_intellisense.js" reference should come after all the other references, otherwise it will fail to function as intended. I nearly opened an issue about it, but received a flash of intuition at the last moment and managed to get the thing working as it should. Hope this helps someone in the future.

**Comment by VeldMuijz** [comment]
Almost lost it until I came accross this comment. In the Usage chapter it doesn't say that you have to reference it in the index.html file. This was the only way to get it working in Visual Studio 2015 RC version
