### ISSUE TITLE
Intellisense inside local functions 

### ISSUE THREAD

**Issue by Wintermoose** [jmbledsoe/angularjs-visualstudio-intellisense#6]
Hi,
I was playing with the code today and I found out that the intellisense doesn't seem to work on the controller's injected parameter, when referred inside local functions. I.e. reference to constant inside someProviderFunction (line 26 of the test file) doesn't resolve.

When I tried similar simplified test (calling function with parameters explicitly) it works, as well as when the someProviderFunction is called inside the controller. 

Do you know what might be causing the problem? Is there any workaround? It seems quite limiting, given the frequently used pattern $scope.someFunction = function()...

Thanks

**Comment by jmatthiesen** [comment]
After some experimenting, it looks like this new code is causing some timeouts. @jmbledsoe do you have some test cases in the project that were fixed as a result of this code? If so, can you point me at them so I can see if changes in the algorithm fix those cases, or break them? If not, can you put together some test cases that didn't work before this code was added?

**Comment by jmbledsoe** [comment]
I don't have test cases right now, but the issue surrounded statement
completion for complex return types of service functions. I will put some
tests together over the weekend and look into setting a recursion limit.

**Comment by jmbledsoe** [comment]
This issue is atrophied unfortunately, so I am closing. I believe we're past the timeouts with the most recent version.
